using System;
using System.Collections.Generic;
using System.Text;

namespace HandoutMiner.Shared
{
    public class PhraseManager : EntityManagerBase
    {
        public PhraseManager(string connection_string) : base(connection_string, "phrase", "BannedPhrases", "PhraseChanges")
        {
        }

        protected override void EnterBans()
        {

            AddBan("10 lantern street text");
            AddBan("10 lantern street");
            AddBan("124th st");
            AddBan("24th");
            AddBan("31st");
            AddBan("648 west 47th street new york");
            AddBan("8");
            AddBan("aberdare forest");
            AddBan("abstract  tattoo  graffiti");
            AddBan("accompachaeological expedition");
            AddBan("africa mombasa");
            AddBan("africa");
            AddBan("ally");
            AddBan("amazon basin");
            AddBan("american armuch");
            AddBan("americas");
            AddBan("arrival");
            AddBan("art  text");
            AddBan("attendance");
            AddBan("aubrey penhew");
            AddBan("augustus larkin text  sketch  art  drawing");
            AddBan("augustus larkin");
            AddBan("authorisies");
            AddBan("belden e");
            AddBan("blank world-wide mover ravdys telegraph service fee_ paid kindly");
            AddBan("blue calfskin text  letter  screenshot  document  text");
            AddBan("book");
            AddBan("businesscard  screenshot  text");
            AddBan("cable letter dl");
            AddBan("cable text");
            AddBan("cablegram");
            AddBan("cairo");
            AddBan("cairo-based portion");
            AddBan("carlyle expedition stop need reliable investigative team stop meet");
            AddBan("carlyle");
            AddBan("cartoon  brick  stone");
            AddBan("cartoon  illustration  portrait");
            AddBan("cartoon  illustration");
            AddBan("cartoon  sketch  text  art  illustration");
            AddBan("carving");
            AddBan("case");
            AddBan("cee cartoon  drawing  text  art");
            AddBan("chain");
            AddBan("child art  portrait  text");
            AddBan("child art  text  wooden  fabric  art  pattern");
            AddBan("china");
            AddBan("close up");
            AddBan("close");
            AddBan("clues");
            AddBan("comment");
            AddBan("companion");
            AddBan("companions");
            AddBan("company");
            AddBan("conclusive");
            AddBan("conditions");
            AddBan("connecticut");
            AddBan("coordination");
            AddBan("copy");
            AddBan("countcarlyle");
            AddBan("criticismand suggestion");
            AddBan("cypress hills cemetery");
            AddBan("dals");
            AddBan("dar o ship  text  vehicle  boat");
            AddBan("dear janak");
            AddBan("dear jawak");
            AddBan("dear mr. carlyle");
            AddBan("dear mr. elias");
            AddBan("deferred cable");
            AddBan("derot orh alt f");
            AddBan("detail text  drawing  sketch");
            AddBan("different murders");
            AddBan("different precincts");
            AddBan("director text  screenshot  typography  design  graphic  font  text");
            AddBan("dr. robert huston");
            AddBan("drawing  monitor  sketch  television");
            AddBan("drawing  sketch  painting  text  art  animal  cartoon");
            AddBan("drawing  sketch  painting");
            AddBan("earth");
            AddBan("east africa");
            AddBan("edward gavigan");
            AddBan("effort rigors");
            AddBan("egypt");
            AddBan("el");
            AddBan("elias jackson");
            AddBan("elias");
            AddBan("elias' belief");
            AddBan("end");
            AddBan("england");
            AddBan("episode");
            AddBan("erica carlyle");
            AddBan("events");
            AddBan("expedition stop please");
            AddBan("explorer augustus larkin");
            AddBan("fact");
            AddBan("fair");
            AddBan("fancy hypatia masters");
            AddBan("fashioncontrary");
            AddBan("first bodies");
            AddBan("focus");
            AddBan("follow");
            AddBan("fon");
            AddBan("font  plaque  text");
            AddBan("forehead");
            AddBan("former \"mentor");
            AddBan("four months");
            AddBan("four other portions");
            AddBan("friend jackson elias");
            AddBan("friends");
            AddBan("friendship");
            AddBan("full rated teleclt");
            AddBan("full zate telegrams");
            AddBan("gaspar du nord");
            AddBan("gaspar figueroa");
            AddBan("gate");
            AddBan("george sorel");
            AddBan("glactle");
            AddBan("goal");
            AddBan("good friend");
            AddBan("great interest");
            AddBan("great rift valley");
            AddBan("greatest flaw");
            AddBan("group");
            AddBan("habitual grin");
            AddBan("hand");
            AddBan("handwriting  furniture  mat  binding");
            AddBan("handwriting  letter  calligraphy  typography  script  document  text");
            AddBan("handwriting  letter  document  text");
            AddBan("handwriting  letter  receipt  text");
            AddBan("handwriting  letter  receipt  typography  document  text");
            AddBan("handwriting  letter  text  bird  document  text");
            AddBan("handwriting  screenshot  letter  font  receipt  text");
            AddBan("handwriting  sketch  stationary  cartoon  envelope  accessory  graffiti");
            AddBan("handwriting  text  design  graphic  letter  typography");
            AddBan("handwriting  text  letter  bird  migration  document  text");
            AddBan("handwriting  text  letter  businesscard  text");
            AddBan("handwriting  text  letter  document  text");
            AddBan("help");
            AddBan("hilton adams mordecai lemming");
            AddBan("history");
            AddBan("hong kong");
            AddBan("horehead");
            AddBan("hotel chelsea");
            AddBan("hotel maury stop");
            AddBan("hudson terminal");
            AddBan("human face  glasses  text  person  spectacles  goggles");
            AddBan("human face  illustration  smile  cartoon  face  painting");
            AddBan("human face  illustration");
            AddBan("human face  portrait");
            AddBan("human face  sketch  face");
            AddBan("human face  statue");
            AddBan("human face  text  sketch");
            AddBan("human face  text");
            AddBan("human face");
            AddBan("human");
            AddBan("human, basis");
            AddBan("hunting");
            AddBan("hypatia masters");
            AddBan("important visitors mombasa");
            AddBan("inadequacy");
            AddBan("india");
            AddBan("indoor  art  accessory  illustration");
            AddBan("indoor  font  screenshot  design");
            AddBan("indoor  sketch  man  art");
            AddBan("indoor  text  art  gallery  room  painting  picture");
            AddBan("information");
            AddBan("innocents");
            AddBan("intention");
            AddBan("interviews");
            AddBan("investigators");
            AddBan("italians");
            AddBan("items");
            AddBan("jack brady");
            AddBan("jackson america");
            AddBan("jackson elias carlton");
            AddBan("jan 19th");
            AddBan("jan");
            AddBan("january 17th");
            AddBan("january");
            AddBan("jesse hughes");
            AddBan("jirón ancash");
            AddBan("joe corey");
            AddBan("johnstone kenyatta");
            AddBan("jonah kensington");
            AddBan("juicy notes");
            AddBan("justice");
            AddBan("justin geoffrey");
            AddBan("key figure");
            AddBan("killer");
            AddBan("knife");
            AddBan("knowledge");
            AddBan("known book");
            AddBan("la");
            AddBan("lake titicaca");
            AddBan("land");
            AddBan("las harvard cambridge");
            AddBan("law office");
            AddBan("lco");
            AddBan("lead");
            AddBan("leader");
            AddBan("leaders");
            AddBan("length");
            AddBan("lenox ave harlem");
            AddBan("letter");
            AddBan("lexington avenue");
            AddBan("life");
            AddBan("lima stop augustus larkin");
            AddBan("lima");
            AddBan("lludson terminal");
            AddBan("local resident hilton adams");
            AddBan("locals");
            AddBan("london");
            AddBan("long interview");
            AddBan("looks");
            AddBan("lt. mark selkirk");
            AddBan("lt. martin poole");
            AddBan("lt. poole");
            AddBan("lt. selkirk");
            AddBan("luis de mendoza");
            AddBan("luis de");
            AddBan("lyle");
            AddBan("m. warren besart text  letter  handwriting  typography  calligraphy ");
            AddBan("mainder");
            AddBan("majority");
            AddBan("man");
            AddBan("mange threads");
            AddBan("manone");
            AddBan("many bearers");
            AddBan("many people");
            AddBan("many skreads");
            AddBan("maroon  book  motif  illustration  picture");
            AddBan("massachusetts");
            AddBan("material");
            AddBan("matters");
            AddBan("meeting");
            AddBan("members");
            AddBan("men");
            AddBan("mercenary");
            AddBan("middle");
            AddBan("mind");
            AddBan("miriam atwright harvard university library");
            AddBan("miss carlyle");
            AddBan("miss erica carlyle");
            AddBan("miss hypatia masters");
            AddBan("miss");
            AddBan("most cases");
            AddBan("motivatribesmen");
            AddBan("mous party");
            AddBan("mr. carlyle");
            AddBan("mr. elias");
            AddBan("mr. harvis");
            AddBan("mr. jack brady");
            AddBan("mr. jackson elias");
            AddBan("mr. royston whittingdon");
            AddBan("mrs. victoria post");
            AddBan("mwm");
            AddBan("mychoanalyse files");
            AddBan("n.y");
            AddBan("naihave");
            AddBan("nails\" nelson");
            AddBan("nairobi");
            AddBan("name");
            AddBan("nayra");
            AddBan("nearby mountain top");
            AddBan("neville jermyn");
            AddBan("new direction");
            AddBan("new murder");
            AddBan("new story");
            AddBan("new york city");
            AddBan("new york pillar/riposte");
            AddBan("new york socialite hypatia masters");
            AddBan("new york socialite");
            AddBan("new york stop jackson elias blank form");
            AddBan("newspaper  font  receipt  text");
            AddBan("newspaper  font  receipt");
            AddBan("next");
            AddBan("night message wlt");
            AddBan("notable discoveries");
            AddBan("note");
            AddBan("noted");
            AddBan("notes");
            AddBan("number");
            AddBan("nyt crimes reporter rebecca shosenberg");
            AddBan("nyt office");
            AddBan("offices");
            AddBan("official version");
            AddBan("officials");
            AddBan("old  abandoned  text  decay  map");
            AddBan("old  art");
            AddBan("old  case  plaque  picture");
            AddBan("old  painting");
            AddBan("old  wall  child art");
            AddBan("old  watercraft  harbor  transport");
            AddBan("one faraz najjar");
            AddBan("one meeting");
            AddBan("one");
            AddBan("ooks");
            AddBan("open-\"almost");
            AddBan("operations");
            AddBan("opinion");
            AddBan("other activities");
            AddBan("other expedition members");
            AddBan("other members");
            AddBan("other volumes");
            AddBan("owner");
            AddBan("owner/editor");
            AddBan("painting");
            AddBan("parallel researches");
            AddBan("part");
            AddBan("past");
            AddBan("patrol");
            AddBan("pcs");
            AddBan("penhew founancient pictographs");
            AddBan("people");
            AddBan("pero");
            AddBan("person  cartoon  couch");
            AddBan("person  cartoon  outdoor  fashion  text  book");
            AddBan("person  man");
            AddBan("person  portrait  text");
            AddBan("person");
            AddBan("peru description");
            AddBan("peru explorer");
            AddBan("peru");
            AddBan("ph.d");
            AddBan("photo");
            AddBan("pick");
            AddBan("pipe");
            AddBan("place");
            AddBan("plains");
            AddBan("plan");
            AddBan("plateau");
            AddBan("point");
            AddBan("points");
            AddBan("possibility");
            AddBan("possible connection");
            AddBan("possible disappearthe");
            AddBan("possible structure");
            AddBan("power");
            AddBan("preliminary identification expertly-conducted trial");
            AddBan("presidente");
            AddBan("prof. anthony cowles");
            AddBan("prof. memesio sanchez sketch  cartoon  drawing  art  illustration");
            AddBan("prof. memesio sanchez");
            AddBan("prof. sanchez");
            AddBan("professor nemesio sanchez");
            AddBan("progress");
            AddBan("project");
            AddBan("prospero house carlton ramsey");
            AddBan("pseudonym");
            AddBan("punctual man");
            AddBan("puno");
            AddBan("purobi");
            AddBan("purpose");
            AddBan("quickest");
            AddBan("quithere");
            AddBan("quotes");
            AddBan("reason");
            AddBan("rebecca shosenburg manhattan");
            AddBan("rebecca shosenburg");
            AddBan("rebecca west");
            AddBan("receives");
            AddBan("regard");
            AddBan("region");
            AddBan("repere peldeve");
            AddBan("report");
            AddBan("reports");
            AddBan("reptile");
            AddBan("republica");
            AddBan("research");
            AddBan("researcher");
            AddBan("researches");
            AddBan("reseveral kikuyu-villager reports");
            AddBan("respite");
            AddBan("response");
            AddBan("reuters");
            AddBan("reuters)-leading expedition");
            AddBan("reuters)-uplands egyptologist");
            AddBan("ringleaders tion");
            AddBan("riposte");
            AddBan("rived");
            AddBan("robert our huston");
            AddBan("roger carlyle");
            AddBan("roger corydon");
            AddBan("roger robert huston");
            AddBan("roger roger");
            AddBan("rogers");
            AddBan("royston whittingdon");
            AddBan("rumor");
            AddBan("rumors");
            AddBan("sacrifice");
            AddBan("safest way");
            AddBan("sam mariga");
            AddBan("same symbol");
            AddBan("sandy labors");
            AddBan("satisfaction");
            AddBan("scanadditional members");
            AddBan("screenshot  document  text");
            AddBan("se. guillermo e. billinghurst");
            AddBan("search");
            AddBan("second half");
            AddBan("second-hand accounts");
            AddBan("service class");
            AddBan("service grain");
            AddBan("set eight");
            AddBan("several good sources");
            AddBan("several languages");
            AddBan("shanghai fuh");
            AddBan("shanghai");
            AddBan("she");
            AddBan("ship");
            AddBan("sign");
            AddBan("silas n kwane");
            AddBan("silas n'kwane");
            AddBan("single sheet");
            AddBan("singular curios");
            AddBan("sir aubrey penhew police representatives");
            AddBan("sir aubrey penhew");
            AddBan("sir");
            AddBan("site");
            AddBan("skeptic");
            AddBan("sketch  art  painting  text  cartoon");
            AddBan("sketch  drawing  art  cartoon  painting  text");
            AddBan("sketch  drawing  art  text  painting");
            AddBan("sketch  drawing  text  book  cartoon  art  illustration");
            AddBan("sketch  drawing  text  painting  art");
            AddBan("sketch  tattoo  abstract  art  cartoon");
            AddBan("sketch  text  cartoon  art");
            AddBan("sketch  text");
            AddBan("skinned vicof");
            AddBan("sky  lake  water  boat  outdoor  watercraft  ship  yellow  vehicle");
            AddBan("sky  water  outdoor  lake  ship  landscape  boat  watercraft");
            AddBan("slaughefforts");
            AddBan("slides");
            AddBan("smile  face  portrait  woman");
            AddBan("soinsseitunica exame");
            AddBan("someone");
            AddBan("something");
            AddBan("sons");
            AddBan("sorts");
            AddBan("source");
            AddBan("southwest pacific");
            AddBan("stance");
            AddBan("standard time");
            AddBan("standard");
            AddBan("stories");
            AddBan("strange");
            AddBan("stratford");
            AddBan("street");
            AddBan("suitable nl night letter sign");
            AddBan("surest");
            AddBan("surrounding site");
            AddBan("sydney");
            AddBan("systematization");
            AddBan("tales");
            AddBan("tative massacre");
            AddBan("telegraphy nm");
            AddBan("tends");
            AddBan("terms");
            AddBan("terror");
            AddBan("text  art  design  pattern");
            AddBan("text  book  cartoon  art  poster  sketch");
            AddBan("text  child art  painting");
            AddBan("text  colorfulness  screenshot  document  text");
            AddBan("text  design  font  screenshot  graphic  graphical user interface");
            AddBan("text  design  screenshot  text");
            AddBan("text  drawing  book");
            AddBan("text  drawing  sketch  book  cartoon  handwriting  illustration");
            AddBan("text  font  screenshot  document  text");
            AddBan("text  font  screenshot  text");
            AddBan("text  letter  design  screenshot  text");
            AddBan("text  letter  handwriting  screenshot  text");
            AddBan("text  map  map");
            AddBan("text  newspaper  screenshot  font  text");
            AddBan("text  newspaper  screenshot");
            AddBan("text  newspaper");
            AddBan("text  painting  statue  cartoon  portrait  spectacles");
            AddBan("text  screenshot  letter  colorfulness  document  text");
            AddBan("text  screenshot  letter  document  text");
            AddBan("text  screenshot  letter  handwriting  receipt  text");
            AddBan("text  screenshot  receipt  text");
            AddBan("text  screenshot  typography  font  text");
            AddBan("text  screenshot");
            AddBan("text");
            AddBan("the way");
            AddBan("the");
            AddBan("tho nddross");
            AddBan("ties");
            AddBan("tig");
            AddBan("time");
            AddBan("tion massacre");
            AddBan("top");
            AddBan("trademark");
            AddBan("trial");
            AddBan("trinidad riso");
            AddBan("trinidad rizo text  art  sketch");
            AddBan("triumph");
            AddBan("two dozen expedition members");
            AddBan("two men");
            AddBan("two months");
            AddBan("united kingdom");
            AddBan("unnamed whites");
            AddBan("usa");
            AddBan("vengeance");
            AddBan("vicious carlyle expeditims");
            AddBan("view");
            AddBan("vintage photo");
            AddBan("w. 1");
            AddBan("waldorfmr");
            AddBan("wallines");
            AddBan("way");
            AddBan("weer alnight");
            AddBan("white  screenshot  receipt");
            AddBan("white  screenshot");
            AddBan("wife");
            AddBan("willa reporters");
            AddBan("wit");
            AddBan("word");
            AddBan("works");
            AddBan("world");
            AddBan("writings");
            AddBan("year");
            AddBan("years");
            AddBan("0403 ssg");

        }

        protected override void EnterChanges()
        {
            AddChange("z\"thoqqua", "thoqqua");
        }
    }
}
